services:
  web:
    build: .
    container_name: receptapp_web
    command: /app/entrypoint.sh
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    environment:
      #- INSTAGRAM_SESSIONID=${INSTAGRAM_SESSIONID}
      - INSTAGRAM_COOKIES=${INSTAGRAM_COOKIES}
      #- INSTAGRAM_CSRFTOKEN=${INSTAGRAM_CSRFTOKEN}
      #- INSTAGRAM_DS_USER_ID=${INSTAGRAM_DS_USER_ID}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: receptapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:alpine
    container_name: receptapp_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    restart: always

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: receptapp_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

volumes:
  postgres_data:
  static_volume:
  media_volume:

