"""
Django settings for receptapp_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# --- PRODUKTION: domän, säkerhet, CORS ---
# Sätt DEBUG=False i produktion!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# Disable rate limiting during test runs to avoid cross-test flakiness.
RATELIMIT_ENABLE = "test" not in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-d-wdou8y26x+uld7froxezkn9d#u*2rkfb&mgyna=^u9+%=zhl')
else:
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
    if not SECRET_KEY:
        # Fallback only if absolutely necessary, but preferably fail hard in prod
        # raise ValueError("DJANGO_SECRET_KEY must be set in production")
        pass 


# ALLOWED_HOSTS måste innehålla din prod-domän (och ev. IP för test)
# Exempel: DJANGO_ALLOWED_HOSTS=api.receptapp.se,receptapp.se,127.0.0.1
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# CORS: endast tillåt iOS-appens domän i produktion
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        'https://app.receptapp.se',  # Byt till din faktiska appdomän
        'https://api.receptapp.se',
    ]

# HTTPS: Se till att servern körs bakom TLS (t.ex. via Nginx/Let’s Encrypt)
# Django kan tvinga HTTPS-redirect:
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Trust the X-Forwarded-Proto header from the proxy (Cloudflare/Nginx)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # CSRF Trusted Origins (needed for Django 4.0+ when behind a proxy)
    # Load from env var, e.g. CSRF_TRUSTED_ORIGINS=https://minarecept.enklagrejer.se,https://another.com
    CSRF_TRUSTED_ORIGINS = [url.strip() for url in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if url.strip()]


# Loggning: logga ej känslig data i produktion
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Anpassade felsidor (404/500)
if not DEBUG:
    # Templates finns i templates/404.html och templates/500.html
    # Django använder dessa automatiskt i production
    pass


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # API (mobile clients)
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'recipes',

    # Social login (Apple, Google, etc)
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.apple',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'receptapp_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'receptapp_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Production: PostgreSQL (via DATABASE_URL env var)
    DATABASE_URL = os.getenv('DATABASE_URL')
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL must be set in production (e.g. postgres://user:pass@host:5432/dbname).")

    try:
        import dj_database_url  # type: ignore
    except ImportError as e:
        raise RuntimeError("Missing dependency: dj-database-url. Install it (pip install -r requirements.txt).") from e

    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            # Disable SSL by default (for Docker/local), enable via env var for RDS
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'False') == 'True',
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'sv-se'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'recipe_list'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'



# --- API / Mobile app configuration ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Allow unauthenticated access to the token endpoint (handled by DRF view permissions).

# --- Social login / allauth config ---
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Kräver e-postverifiering
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 600  # 10 min
SOCIALACCOUNT_AUTO_SIGNUP = True

# E-postinställningar för produktion (lägg in i miljövariabler)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'webmaster@localhost'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@receptapp.se')

SOCIALACCOUNT_PROVIDERS = {
    'apple': {
        # Apple Sign-In credentials (lägg in i miljövariabler eller secrets!)
        # Skapa och ladda ner en private key (p8) i Apple Developer Portal.
        # Sätt dessa i din miljö (t.ex. .env, GitHub Secrets, eller servern):
        #   APPLE_CLIENT_ID, APPLE_TEAM_ID, APPLE_KEY, APPLE_SECRET
        'APP': {
            'client_id': os.getenv('APPLE_CLIENT_ID', ''),
            'team_id': os.getenv('APPLE_TEAM_ID', ''),
            'key': os.getenv('APPLE_KEY', ''),  # Key ID
            'secret': os.getenv('APPLE_SECRET', ''),  # Private key (p8)
        },
    },
}
