name: ReceptAppiOS
options:
  deploymentTarget:
    iOS: "16.0"

targets:
  ReceptAppiOS:
    type: application
    platform: iOS
    sources:
      - path: ReceptAppiOS/Sources
    resources:
      - path: ReceptAppiOS/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: se.enklagrejer.minarecept
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
        CODE_SIGN_ENTITLEMENTS: ReceptAppiOS/ReceptAppiOS.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: MinaRecept
        INFOPLIST_KEY_API_BASE_URL: https://minarecept.enklagrejer.se/api/
      configs:
        Release:
          INFOPLIST_KEY_API_BASE_URL: https://minarecept.enklagrejer.se/api/
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
          APP_GROUPS:
            - group.se.enklagrejer.minarecept
        Debug:
          #INFOPLIST_KEY_API_BASE_URL: http://127.0.0.1:8000/api/
          INFOPLIST_KEY_API_BASE_URL: http://192.168.123.239:8000/api/
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
          APP_GROUPS:
            - group.se.enklagrejer.minarecept
    info:
      path: ReceptAppiOS/Resources/Info.plist
      properties:
        API_BASE_URL: $(INFOPLIST_KEY_API_BASE_URL)
        CFBundleURLTypes:
          - CFBundleURLName: se.enklagrejer.minarecept
            CFBundleURLSchemes:
              - receptapp
        NSAppTransportSecurity:
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
            127.0.0.1:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        UILaunchScreen: {}
    dependencies:
      - target: ReceptAppShare

  ReceptAppShare:
    type: app-extension
    platform: iOS
    sources:
      - path: ReceptAppShare
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_BUNDLE_IDENTIFIER: se.enklagrejer.minarecept.share
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
        CODE_SIGN_ENTITLEMENTS: ReceptAppShare/ReceptAppShare.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: MinaRecept Share
        INFOPLIST_KEY_API_BASE_URL: https://minarecept.enklagrejer.se/api/
      configs:
        Release:
          INFOPLIST_KEY_API_BASE_URL: https://minarecept.enklagrejer.se/api/
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
          APP_GROUPS:
            - group.se.enklagrejer.minarecept
        Debug:
          #INFOPLIST_KEY_API_BASE_URL: http://127.0.0.1:8000/api/
          INFOPLIST_KEY_API_BASE_URL: http://192.168.123.239:8000/api/
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
          APP_GROUPS:
            - group.se.enklagrejer.minarecept
    info:
      path: ReceptAppShare/Info.plist
      properties:
        CFBundleDisplayName: MinaRecept Share
        API_BASE_URL: $(INFOPLIST_KEY_API_BASE_URL)
        NSAppTransportSecurity:
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
            127.0.0.1:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule: |
              SUBQUERY (
                  extensionItems,
                  $extensionItem,
                  SUBQUERY (
                      $extensionItem.attachments,
                      $attachment,
                      ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.url" ||
                      ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.plain-text"
                  ).@count >= 1
              ).@count >= 1
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController

  ReceptAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ReceptAppiOS/Tests
    dependencies:
      - target: ReceptAppiOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: se.enklagrejer.minarecept.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ReceptAppiOS.app/ReceptAppiOS"
        ENABLE_TESTING_SEARCH_PATHS: YES
        GENERATE_INFOPLIST_FILE: YES

  ReceptAppShareTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ReceptAppShareTests
    dependencies:
      - target: ReceptAppShare
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: se.enklagrejer.minarecept.sharetests
        ENABLE_TESTING_SEARCH_PATHS: YES
        GENERATE_INFOPLIST_FILE: YES
