upstream receptapp {
    server web:8000;
}

server {
    listen 80;

    # Statiska filer
    location /static/ {
        alias /app/staticfiles/;
    }

    # Mediafiler (uppladdade bilder)
    location /media/ {
        alias /app/media/;
    }

    # Allt annat skickas till Django (Gunicorn)
    location / {
        proxy_pass http://receptapp;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        client_max_body_size 20M; # Tillåt större bilduppladdningar
    }
}

