# Generated by Django 6.0 on 2025-12-22 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(help_text='List ingredients, one per line')),
                ('steps', models.TextField(help_text='Describe the cooking steps')),
                ('cooking_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Enkel'), ('medium', 'Medel'), ('hard', 'Avancerad')], default='medium', max_length=10)),
                ('dish_type', models.CharField(choices=[('everyday', 'Vardagsmat'), ('party', 'Fest'), ('dessert', 'Efterrätt'), ('vegetarian', 'Vegetariskt'), ('other', 'Övrigt')], default='everyday', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=200)),
                ('servings', models.PositiveIntegerField(default=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Måndag'), ('tue', 'Tisdag'), ('wed', 'Onsdag'), ('thu', 'Torsdag'), ('fri', 'Fredag'), ('sat', 'Lördag'), ('sun', 'Söndag')], max_length=3)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day', 'recipe')},
            },
        ),
    ]
