# Generated by Django 6.0 on 2025-12-22 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recept', 'verbose_name_plural': 'Recept'},
        ),
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'verbose_name': 'Veckoplan', 'verbose_name_plural': 'Veckoplaner'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Tid i minuter', verbose_name='Tillagningstid'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Skapad'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Enkel'), ('medium', 'Medel'), ('hard', 'Avancerad')], default='medium', max_length=10, verbose_name='Svårighetsgrad'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('everyday', 'Vardagsmat'), ('party', 'Fest'), ('dessert', 'Efterrätt'), ('vegetarian', 'Vegetariskt'), ('other', 'Övrigt')], default='everyday', max_length=20, verbose_name='Typ av rätt'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Lista ingredienser, en per rad', verbose_name='Ingredienser'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='Antal portioner'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(help_text='Beskriv tillagningsstegen', verbose_name='Gör så här'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, help_text='Kommaseparerade taggar', max_length=200, verbose_name='Taggar'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Uppdaterad'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='day',
            field=models.CharField(choices=[('mon', 'Måndag'), ('tue', 'Tisdag'), ('wed', 'Onsdag'), ('thu', 'Torsdag'), ('fri', 'Fredag'), ('sat', 'Lördag'), ('sun', 'Söndag')], max_length=3, verbose_name='Dag'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recept'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare'),
        ),
    ]
