# Generated by Django 6.0 on 2025-12-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_shoppinglistitem_options_recipe_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Huvudlista'),
        ),
    ]
