# Generated by Django 6.0 on 2025-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_shoppinglist_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('breakfast', 'Frukost'), ('lunch', 'Lunch'), ('dinner', 'Middag'), ('appetizer', 'Förrätt'), ('dessert', 'Efterrätt'), ('snack', 'Mellanmål'), ('everyday', 'Vardagsmat'), ('party', 'Fest'), ('vegetarian', 'Vegetariskt'), ('other', 'Övrigt')], default='everyday', max_length=20, verbose_name='Typ av rätt'),
        ),
    ]
