# Generated by Django 6.0 on 2025-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenu',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='Antal portioner'),
        ),
    ]
