# Generated by Django 6.0 on 2025-12-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_weeklymenu_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='Antal portioner'),
        ),
    ]
