# Generated by Django 6.0.1 on 2026-01-09 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_merge_everyday_to_lunch_dinner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Namn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Uppdaterad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
            ],
            options={
                'verbose_name': 'Kokbok',
                'verbose_name_plural': 'Kokböcker',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookbookRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_recipes', to='recipes.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_recipes', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Kokbok-recept',
                'verbose_name_plural': 'Kokbok-recept',
                'unique_together': {('cookbook', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='cookbooks', through='recipes.CookbookRecipe', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='cookbook',
            unique_together={('user', 'name')},
        ),
    ]
